<?php

/**
 * Implements hook_nodeapi()
 *
 * Loads ALL uploaded ssh keys into the server_master server node.
 */
function aegir_ssh_node_load($nodes, $types) {
  if (count(array_intersect(array('server'), $types)) == 0) {
    return;
  }

  // Only save keys for @hostmaster's own web server.
  foreach ($nodes as &$node) {
    if ($node->nid == variable_get('hosting_own_web_server', NULL)) {
      $node->authorized_keys = array();
      $query = db_query('SELECT value FROM {sshkey}');
      while ($result = $query->fetchObject()) {
        $node->authorized_keys[] = $result->value;
      }
    }
  }
}